#define YY_parse_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from pass2.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "pass2.y"

#include "functions.h"
FILE *op,*intr;
extern FILE *yyin;
char *c,h[14],h1[14];
int f=0,locctr=0,mod=0,lineno=1,s=0;
int err[20],front=0;
extern struct instrn t;
int yyerrstatus,errf=0;
SYMBOL *temp;

#line 13 "pass2.y"
typedef union {
  int num;
  char str[30];
} yy_parse_stype;
#define YY_parse_STYPE yy_parse_stype
#ifndef YY_USE_CLASS
#define YYSTYPE yy_parse_stype
#endif

#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parse_BISON 1

#ifndef YY_parse_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parse_COMPATIBILITY 1
 #else
  #define  YY_parse_COMPATIBILITY 0
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parse_LTYPE
   #define YY_parse_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parse_STYPE 
   #define YY_parse_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parse_DEBUG
   #define  YY_parse_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parse_USE_GOTO
  #define YY_parse_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parse_USE_GOTO
 #define YY_parse_USE_GOTO 0
#endif

#ifndef YY_parse_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parse_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parse_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parse_DEBUG */
#endif


#ifndef YY_parse_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parse_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parse_LSP_NEEDED
#ifndef YY_parse_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parse_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parse_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parse_STYPE
#define YY_parse_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parse_PARSE
#define YY_parse_PARSE yyparse
#endif
#ifndef YY_parse_LEX
#define YY_parse_LEX yylex
#endif
#ifndef YY_parse_LVAL
#define YY_parse_LVAL yylval
#endif
#ifndef YY_parse_LLOC
#define YY_parse_LLOC yylloc
#endif
#ifndef YY_parse_CHAR
#define YY_parse_CHAR yychar
#endif
#ifndef YY_parse_NERRS
#define YY_parse_NERRS yynerrs
#endif
#ifndef YY_parse_DEBUG_FLAG
#define YY_parse_DEBUG_FLAG yydebug
#endif
#ifndef YY_parse_ERROR
#define YY_parse_ERROR yyerror
#endif

#ifndef YY_parse_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parse_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parse_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parse_PARSE_PARAM
  #define YY_parse_PARSE_PARAM void
 #endif
#endif

#if YY_parse_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parse_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parse_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parse_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parse_PURE
#  ifndef YYPURE
#    define YYPURE YY_parse_PURE
#  endif
#endif

#ifdef YY_parse_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parse_DEBUG 
#  endif
#endif

#ifndef YY_parse_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parse_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parse_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parse_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	LABEL	258
#define	STR	259
#define	ARITH	260
#define	LOG	261
#define	DTTF	262
#define	CTTF	263
#define	IO	264
#define	REG8	265
#define	REG16	266
#define	MEM	267
#define	IBYTE	268
#define	IWORD	269
#define	CL	270
#define	CON	271
#define	COLON	272
#define	E	273
#define	DB	274
#define	DW	275


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parse_CLASS
#define YY_parse_CLASS parse
#endif
#ifndef YY_parse_INHERIT
#define YY_parse_INHERIT
#endif
#ifndef YY_parse_MEMBERS
#define YY_parse_MEMBERS 
#endif
#ifndef YY_parse_LEX_BODY
#define YY_parse_LEX_BODY  
#endif
#ifndef YY_parse_ERROR_BODY
#define YY_parse_ERROR_BODY  
#endif
#ifndef YY_parse_CONSTRUCTOR_PARAM
#define YY_parse_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parse_CONSTRUCTOR_CODE
#define YY_parse_CONSTRUCTOR_CODE
#endif
#ifndef YY_parse_CONSTRUCTOR_INIT
#define YY_parse_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parse_USE_CONST_TOKEN
#define YY_parse_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parse_USE_CONST_TOKEN != 0
#ifndef YY_parse_ENUM_TOKEN
#define YY_parse_ENUM_TOKEN yy_parse_enum_token
#endif
#endif

class YY_parse_CLASS YY_parse_INHERIT
{
public: 
#if YY_parse_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int LABEL;
static const int STR;
static const int ARITH;
static const int LOG;
static const int DTTF;
static const int CTTF;
static const int IO;
static const int REG8;
static const int REG16;
static const int MEM;
static const int IBYTE;
static const int IWORD;
static const int CL;
static const int CON;
static const int COLON;
static const int E;
static const int DB;
static const int DW;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parse_ENUM_TOKEN { YY_parse_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,LABEL=258
	,STR=259
	,ARITH=260
	,LOG=261
	,DTTF=262
	,CTTF=263
	,IO=264
	,REG8=265
	,REG16=266
	,MEM=267
	,IBYTE=268
	,IWORD=269
	,CL=270
	,CON=271
	,COLON=272
	,E=273
	,DB=274
	,DW=275


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parse_PARSE (YY_parse_PARSE_PARAM);
 virtual void YY_parse_ERROR(char *msg) YY_parse_ERROR_BODY;
#ifdef YY_parse_PURE
#ifdef YY_parse_LSP_NEEDED
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL,YY_parse_LTYPE *YY_parse_LLOC) YY_parse_LEX_BODY;
#else
 virtual int  YY_parse_LEX (YY_parse_STYPE *YY_parse_LVAL) YY_parse_LEX_BODY;
#endif
#else
 virtual int YY_parse_LEX() YY_parse_LEX_BODY;
 YY_parse_STYPE YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
 YY_parse_LTYPE YY_parse_LLOC;
#endif
 int   YY_parse_NERRS;
 int    YY_parse_CHAR;
#endif
#if YY_parse_DEBUG != 0
 int YY_parse_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM);
public:
 YY_parse_MEMBERS 
};
/* other declare folow */
#if YY_parse_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parse_CLASS::LABEL=258;
const int YY_parse_CLASS::STR=259;
const int YY_parse_CLASS::ARITH=260;
const int YY_parse_CLASS::LOG=261;
const int YY_parse_CLASS::DTTF=262;
const int YY_parse_CLASS::CTTF=263;
const int YY_parse_CLASS::IO=264;
const int YY_parse_CLASS::REG8=265;
const int YY_parse_CLASS::REG16=266;
const int YY_parse_CLASS::MEM=267;
const int YY_parse_CLASS::IBYTE=268;
const int YY_parse_CLASS::IWORD=269;
const int YY_parse_CLASS::CL=270;
const int YY_parse_CLASS::CON=271;
const int YY_parse_CLASS::COLON=272;
const int YY_parse_CLASS::E=273;
const int YY_parse_CLASS::DB=274;
const int YY_parse_CLASS::DW=275;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parse_CLASS::token */
#endif
/*apres const  */
YY_parse_CLASS::YY_parse_CLASS(YY_parse_CONSTRUCTOR_PARAM) YY_parse_CONSTRUCTOR_INIT
{
#if YY_parse_DEBUG != 0
YY_parse_DEBUG_FLAG=0;
#endif
YY_parse_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		71
#define	YYFLAG		-32768
#define	YYNTBASE	25

#define YYTRANSLATE(x) ((unsigned)(x) <= 275 ? yytranslate[x] : 42)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,    17,     2,     2,     2,     2,    22,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
    23,     2,    24,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    18,    19,    20,    21
};

#if YY_parse_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     3,     4,     7,    10,    14,    16,    19,    22,    25,
    27,    31,    33,    37,    39,    41,    43,    45,    47,    50,
    53,    56,    58,    63,    68,    71,    73,    75,    78,    81,
    84,    87,    91,    95,    99,   103,   105,   107,   110,   112,
   116,   118,   120,   122,   124,   126,   128,   130,   132
};

static const short yyrhs[] = {    26,
    25,     0,     0,    27,    19,     0,    31,    19,     0,     3,
    18,    19,     0,    19,     0,     3,    28,     0,    21,    29,
     0,    20,    30,     0,     4,     0,    14,    17,    29,     0,
    14,     0,    13,    17,    30,     0,    13,     0,    32,     0,
    33,     0,    35,     0,    36,     0,     5,    37,     0,     5,
    40,     0,     5,    38,     0,     5,     0,     6,    41,    17,
    34,     0,     6,    39,    17,    34,     0,     6,    37,     0,
    15,     0,    22,     0,     7,    37,     0,     7,    38,     0,
     8,     3,     0,     8,    40,     0,    41,    17,    39,     0,
    39,    17,    41,     0,    41,    17,    41,     0,    39,    17,
    39,     0,    41,     0,    39,     0,    12,    40,     0,    12,
     0,    23,    40,    24,     0,     3,     0,     5,     0,     6,
     0,     7,     0,     8,     0,    14,     0,    13,     0,    10,
     0,    11,     0
};

#endif

#if (YY_parse_DEBUG != 0) || defined(YY_parse_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    52,    53,    56,    57,    58,    66,    68,    72,    73,    74,
    76,    77,    79,    80,    82,    85,    88,    91,    95,    96,
    97,    98,   100,   101,   102,   105,   106,   108,   109,   112,
   123,   125,   137,   142,   146,   148,   149,   153,   156,   157,
   159,   166,   167,   168,   169,   172,   173,   175,   176
};

static const char * const yytname[] = {   "$","error","$illegal.","LABEL","STR",
"ARITH","LOG","DTTF","CTTF","IO","REG8","REG16","MEM","IBYTE","IWORD","CL","CON",
"','","COLON","E","DB","DW","'1'","'['","']'","S","N","VAR","VAL","NWORDS","NBYTES",
"INSTR","ARITHMETIC","LOGICAL","STEP","DATATRANS","CTRLTRANS","REGMEM","RM",
"MEMORY","CONST","REG",""
};
#endif

static const short yyr1[] = {     0,
    25,    25,    26,    26,    26,    26,    27,    28,    28,    28,
    29,    29,    30,    30,    31,    31,    31,    31,    32,    32,
    32,    32,    33,    33,    33,    34,    34,    35,    35,    36,
    36,    37,    37,    37,    37,    38,    38,    39,    39,    39,
    39,    39,    39,    39,    39,    40,    40,    41,    41
};

static const short yyr2[] = {     0,
     2,     0,     2,     2,     3,     1,     2,     2,     2,     1,
     3,     1,     3,     1,     1,     1,     1,     1,     2,     2,
     2,     1,     4,     4,     2,     1,     1,     2,     2,     2,
     2,     3,     3,     3,     3,     1,     1,     2,     1,     3,
     1,     1,     1,     1,     1,     1,     1,     1,     1
};

static const short yydefact[] = {     2,
     0,    22,     0,     0,     0,     6,     2,     0,     0,    15,
    16,    17,    18,    10,     0,     0,     0,     7,    41,    42,
    43,    44,    45,    48,    49,    39,    47,    46,     0,    19,
    21,    37,    20,    36,    25,     0,     0,    28,    29,    30,
    31,     1,     3,     4,     5,    14,     9,    12,     8,    38,
     0,     0,     0,     0,     0,     0,     0,    40,    35,    33,
    32,    34,    26,    27,    24,    23,    13,    11,     0,     0,
     0
};

static const short yydefgoto[] = {    42,
     7,     8,    18,    49,    47,     9,    10,    11,    65,    12,
    13,    30,    31,    32,    33,    34
};

static const short yypact[] = {    64,
    -2,     0,    54,    54,    27,-32768,    64,   -10,    18,-32768,
-32768,-32768,-32768,-32768,    19,     2,     3,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,     7,-32768,-32768,     7,-32768,
-32768,    22,-32768,    25,-32768,    28,    29,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,    30,-32768,    41,-32768,-32768,
    24,    54,    54,    21,    21,     2,     3,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,    63,    68,
-32768
};

static const short yypgoto[] = {    73,
-32768,-32768,-32768,    17,    20,-32768,-32768,-32768,    23,-32768,
-32768,    31,    71,    -3,    -4,     1
};


#define	YYLAST		83


static const short yytable[] = {    36,
    41,    14,    19,    37,    20,    21,    22,    23,    43,    24,
    25,    26,    27,    28,    46,    15,    48,    16,    17,    27,
    28,    50,    29,    19,    51,    20,    21,    22,    23,    40,
    24,    25,    26,    35,    38,    63,    44,    45,    52,    27,
    28,    53,    64,    29,    54,    55,    56,    58,    59,    61,
    59,    61,    60,    62,    60,    62,    19,    57,    20,    21,
    22,    23,    70,    24,    25,    26,     1,    71,     2,     3,
     4,     5,    69,    68,    39,    67,    29,    66,     0,     0,
     0,     0,     6
};

static const short yycheck[] = {     3,
     5,     4,     3,     3,     5,     6,     7,     8,    19,    10,
    11,    12,    13,    14,    13,    18,    14,    20,    21,    13,
    14,    26,    23,     3,    29,     5,     6,     7,     8,     3,
    10,    11,    12,     3,     4,    15,    19,    19,    17,    13,
    14,    17,    22,    23,    17,    17,    17,    24,    52,    53,
    54,    55,    52,    53,    54,    55,     3,    17,     5,     6,
     7,     8,     0,    10,    11,    12,     3,     0,     5,     6,
     7,     8,     0,    57,     4,    56,    23,    55,    -1,    -1,
    -1,    -1,    19
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parse_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parse_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parse_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parse_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parse_CHAR = (token), YY_parse_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parse_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parse_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parse_PURE
/* UNPURE */
#define YYLEX           YY_parse_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parse_CHAR;                      /*  the lookahead symbol        */
YY_parse_STYPE      YY_parse_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parse_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parse_LSP_NEEDED
YY_parse_LTYPE YY_parse_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parse_LSP_NEEDED
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL, &YY_parse_LLOC)
#else
#define YYLEX           YY_parse_LEX(&YY_parse_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parse_DEBUG != 0
int YY_parse_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parse_CLASS::
#endif
     YY_parse_PARSE(YY_parse_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parse_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parse_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parse_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parse_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parse_LTYPE *yyls = yylsa;
  YY_parse_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parse_PURE
  int YY_parse_CHAR;
  YY_parse_STYPE YY_parse_LVAL;
  int YY_parse_NERRS;
#ifdef YY_parse_LSP_NEEDED
  YY_parse_LTYPE YY_parse_LLOC;
#endif
#endif

  YY_parse_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parse_NERRS = 0;
  YY_parse_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parse_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parse_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parse_LSP_NEEDED
      YY_parse_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parse_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parse_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parse_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parse_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parse_LSP_NEEDED
      yyls = (YY_parse_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parse_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parse_CHAR == YYEMPTY)
    {
#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parse_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parse_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parse_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parse_CHAR);

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parse_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parse_CHAR, YY_parse_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parse_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parse_CHAR != YYEOF)
    YY_parse_CHAR = YYEMPTY;

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 2:
#line 53 "pass2.y"
{printf("\n PASS 2 complete.....");;
    break;}
case 3:
#line 56 "pass2.y"
{tohex(locctr,h,4);printf("%4d\t%s\t",++lineno,h);fscanf(intr," %s ",h);locctr=toint(h,4);;
    break;}
case 4:
#line 57 "pass2.y"
{tohex(locctr,h,4);printf("%4d\t%s\t",++lineno,h);fscanf(intr," %s ",h);locctr=toint(h,4);;
    break;}
case 5:
#line 58 "pass2.y"
{ if((temp =search_symbol(yyvsp[-2].str))!=NULL&& temp->flag!=0)
					printf("\t Symbol declared/repeated error\n");
					
					tohex(locctr,h,4);
					printf("%4d\t%s\t",++lineno,h);
					fscanf(intr," %s ",h);
					locctr=toint(h,4);
			    ;
    break;}
case 6:
#line 66 "pass2.y"
{printf("%4d\t",++lineno);;
    break;}
case 7:
#line 68 "pass2.y"
{if((temp =search_symbol(yyvsp[-1].str))!=NULL&& temp->flag!=0)
                    printf("\n Symbol repeated here error\n");
			   ;
    break;}
case 8:
#line 72 "pass2.y"
{convert(yyvsp[0].str,h);printf("%s\n",h);fprintf(op,"%s\n",h);;
    break;}
case 9:
#line 73 "pass2.y"
{convert(yyvsp[0].str,h);printf("%s\n",h);fprintf(op,"%s\n",h);;
    break;}
case 10:
#line 74 "pass2.y"
{convert(yyvsp[0].str,h);printf("%s\n",h);fprintf(op,"%s\n",h);;
    break;}
case 11:
#line 76 "pass2.y"
{yyvsp[-2].str[4]='\0';strcat(yyvsp[-2].str,yyvsp[0].str);strcpy(yyval.str,yyvsp[-2].str);;
    break;}
case 12:
#line 77 "pass2.y"
{yyvsp[0].str[4]='\0'; strcpy(yyval.str,yyvsp[0].str);;
    break;}
case 13:
#line 79 "pass2.y"
{yyvsp[-2].str[2]='\0';strcat(yyvsp[-2].str,yyvsp[0].str);strcpy(yyval.str,yyvsp[-2].str);;
    break;}
case 14:
#line 80 "pass2.y"
{yyvsp[0].str[2]='\0';strcpy(yyval.str,yyvsp[0].str);;
    break;}
case 15:
#line 82 "pass2.y"
{if(!errf) printf("\t%s\n",yyvsp[0].str);
					   else printf("\tERROR\n");
		 			 fprintf(op,"%s\n",yyvsp[0].str);mod=f=s=errf=0; ;
    break;}
case 16:
#line 85 "pass2.y"
{if(!errf) printf("\t%s\n",yyvsp[0].str);
				 else printf("\tERROR\n");
		 		 fprintf(op,"%s\n",yyvsp[0].str);mod=f=s=errf=0;;
    break;}
case 17:
#line 88 "pass2.y"
{if(!errf) printf("\t%s\n",yyvsp[0].str);
			 else printf("\tERROR\n");
		 	 fprintf(op,"%s\n",yyvsp[0].str);mod=f=s=errf=0;;
    break;}
case 18:
#line 91 "pass2.y"
{if(!errf) printf("\t%s\n",yyvsp[0].str);
			 else printf("\tERROR\n");
		 	 fprintf(op,"%s\n",yyvsp[0].str);mod=f=s=errf=0;;
    break;}
case 19:
#line 95 "pass2.y"
{get_code(yyvsp[-1].str,h,0+(f==2));addhex(h,yyvsp[0].str,yyval.str);;
    break;}
case 20:
#line 96 "pass2.y"
{get_code(yyvsp[-1].str,h,2);addhex(h,yyvsp[0].str,yyval.str);;
    break;}
case 21:
#line 97 "pass2.y"
{get_code(yyvsp[-1].str,h,0);addhex(h,yyvsp[0].str,yyval.str);;
    break;}
case 22:
#line 98 "pass2.y"
{get_code(yyvsp[0].str,h,0);strcpy(yyval.str,h);printf("\t");;
    break;}
case 23:
#line 100 "pass2.y"
{getrm(yyvsp[-2].num,0,3,h);addhex(h,yyvsp[0].str,h);get_code(yyvsp[-3].str,h1,0);addhex(h,h1,yyval.str);;
    break;}
case 24:
#line 101 "pass2.y"
{getrm(yyvsp[-2].num,0,mod,h);addhex(h,yyvsp[0].str,h);get_code(yyvsp[-3].str,h1,0);addhex(h,h1,yyval.str);;
    break;}
case 25:
#line 102 "pass2.y"
{get_code(yyvsp[-1].str,h,0+(f==2));addhex(h,yyvsp[0].str,yyval.str);;
    break;}
case 26:
#line 105 "pass2.y"
{strcpy(yyval.str,"02");;
    break;}
case 27:
#line 106 "pass2.y"
{strcpy(yyval.str,"00");;
    break;}
case 28:
#line 108 "pass2.y"
{get_code(yyvsp[-1].str,h,0+(f==2));addhex(h,yyvsp[0].str,yyval.str);;
    break;}
case 29:
#line 109 "pass2.y"
{get_code(yyvsp[-1].str,h,2);addhex(h,yyvsp[0].str,yyval.str);;
    break;}
case 30:
#line 112 "pass2.y"
{get_code(yyvsp[-1].str,h,0);
			 Symbol *temp=search_symbol(yyvsp[0].str);
			 if(temp==NULL)
		  	  {strcpy(h1,"");yyerror(2);}
			 else
			  { tohex(locctr-temp->addrs,h1,4); //find out the difference
			    if(h1[0] =='F' && h1[1]=='F')  //in case of forward jump, addrs= FFF... so the first 2F get added with opcode **
			   	{ h1[0]='0'; h1[1]='0'; }   //so make them 00 so that 0+*=*
			   }
			   addhex(h,h1,yyval.str);  //concatenating the hex values here 
			  ;
    break;}
case 31:
#line 123 "pass2.y"
{get_code(yyvsp[-1].str,h,0);addhex(h,yyvsp[0].str,yyval.str);;
    break;}
case 32:
#line 125 "pass2.y"
{if(f%10==2)
			 {getrm(yyvsp[-2].num,0,3,yyval.str);
			  tohex(yyvsp[0].num,h,4-f/5-s);
			  strcat(yyval.str,h);
			  if((f/5==0)&&((yyvsp[-2].num<8&&s==0)||(yyvsp[-2].num>=8&&s==2))) yyerror(2);}
			 else
			  {getrm(((f%10==1)? 6:yyvsp[0].num%8),yyvsp[-2].num,mod,yyval.str);
			   if(f/10==1) 
			    {tohex(yyvsp[0].num/8,h,4-s);strcat(yyval.str,h);}
			   }
			 mod=0;
 			;
    break;}
case 33:
#line 137 "pass2.y"
{getrm(((f%10==1)? yyvsp[-2].num%8:6),yyvsp[0].num,mod,h);addhex(h,"02",yyval.str); 
			 if(f/10==1) 
			  {tohex(yyvsp[-2].num/8,h,4-s);strcat(yyval.str,h);}
			 mod=0;f=0;
			 ;
    break;}
case 34:
#line 142 "pass2.y"
{getrm(yyvsp[0].num,yyvsp[-2].num,3,h);strcpy(yyval.str,h);
			   if(f<=1&&((yyvsp[-2].num<8&&yyvsp[0].num>=8)||(yyvsp[0].num<8&&yyvsp[-2].num>=8))) 
			   		yyerror(1);
			  ;
    break;}
case 35:
#line 146 "pass2.y"
{if(f!=2) yyerror(3);;
    break;}
case 36:
#line 148 "pass2.y"
{getrm(yyvsp[0].num,0,3,h);strcpy(yyval.str,h);;
    break;}
case 37:
#line 149 "pass2.y"
{getrm(yyvsp[0].num,0,mod,h);
						 strcpy(yyval.str,h);
						 mod=0;;
    break;}
case 38:
#line 153 "pass2.y"
{yyval.num=yyvsp[-1].num+(toint(yyvsp[0].str,strlen(yyvsp[0].str)-1)<<3);
						mod=(strlen(yyvsp[0].str)-1)/2;
						f=10;;
    break;}
case 39:
#line 156 "pass2.y"
{yyval.num=yyvsp[0].num;;
    break;}
case 40:
#line 157 "pass2.y"
{yyval.num=toint(yyvsp[-1].str,strlen(yyvsp[-1].str)-1)<<3;
						  f=11;;
    break;}
case 41:
#line 159 "pass2.y"
{Symbol *temp=search_symbol(yyvsp[0].str);
			 if(temp==NULL)
		  	  {yyval.num=0;yyerror(2);}
			else
			  yyval.num=locctr-temp->addrs;
			 f=12;
			;
    break;}
case 42:
#line 166 "pass2.y"
{yyerror(0);;
    break;}
case 43:
#line 167 "pass2.y"
{yyerror(0);;
    break;}
case 44:
#line 168 "pass2.y"
{yyerror(0);;
    break;}
case 45:
#line 169 "pass2.y"
{yyerror(0);;
    break;}
case 46:
#line 172 "pass2.y"
{strcpy(yyval.str,yyvsp[0].str);s=0;;
    break;}
case 47:
#line 173 "pass2.y"
{strcpy(yyval.str,yyvsp[0].str);s=2;;
    break;}
case 48:
#line 175 "pass2.y"
{yyval.num=yyvsp[0].num;;
    break;}
case 49:
#line 176 "pass2.y"
{yyval.num=yyvsp[0].num;;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parse_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parse_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parse_LLOC.first_line;
      yylsp->first_column = YY_parse_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parse_NERRS;

#ifdef YY_parse_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parse_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parse_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parse_ERROR_VERBOSE */
	YY_parse_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parse_CHAR == YYEOF)
	YYABORT;

#if YY_parse_DEBUG != 0
      if (YY_parse_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parse_CHAR, yytname[yychar1]);
#endif

      YY_parse_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parse_LSP_NEEDED
  yylsp--;
#endif

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parse_DEBUG != 0
  if (YY_parse_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parse_LVAL;
#ifdef YY_parse_LSP_NEEDED
  *++yylsp = YY_parse_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 178 "pass2.y"


int yyerror(int errcode)
{
  if(!errf)
   err[front++]=errcode+(lineno<<3);
  errf=1;
  return 0;
}

void disperr()
{
  int i=0;
  if(front) printf("\n\n%d errors found!!",front);
  for(;i<front;i++)
   switch(err[i]%8)
   {
     case 0:printf("\nError %d:Invalid operand",err[i]/8);break;
     case 1:printf("\nError %d:Missmatch in size of operands",err[i]/8);break;
     case 2:printf("\nError %d:Label not defined",err[i]/8);break;
     case 3:printf("\nError %d:Atleast 1 operand must be a register",err[i]/8);break;
     default:printf("\nFatal Error %d:Unable to parse",err[i]/8);break;
   }
}

int main()
{


FILE *fp;
    char line[10];
    fp =fopen("opcode.obj","r");
    printf("\n\nOpcode generated after second parse\n");
    while(fgets(line,10,fp))
    printf("%s",line);

	


  read_symtab();
  //print_symtab();
  printf("\n\nLineNum LOCCTR  INSTRUCTION      OPCODE\n\n");
  initopcodes();
  intr=fopen("inter.txt","r");
  fscanf(intr," %s ",h);
  locctr=toint(h,4);
 	printf("%4d\t0000\t",lineno);
  op=fopen("opcode.obj","w");
  yyin=fopen("prog.asm","r");
  yyparse();
  disperr();
  printf("\n\n");
  
  
}
